from fastapi import APIRouter
from app.api.v1 import auth, reservations, availability, housekeeping, frontdesk, rates, helpdesk, reports, dashboards, rooms, bookings, precheckin, users, guests, staff, room_types, payment_methods, admin, otp, guest_ai, guest_assistant, agi_assistant, runner, maintenance, notifications, feedback, admin_ai, analytics, revenue_intelligence, reputation, crm_ai, crm_ai_extended, overbooking, guest_chat, inventory, attendance, folio, rbac, hotel_config, tax, corporate, ar, preauth, transaction_codes, audit_log, cashier_session, room_moves, paymaster, pos_closure, audit_pack, multi_room
from app.api.v1 import reputation_alerts, reputation_automation, reputation_categories, reputation_templates

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/v1/auth", tags=["auth"])
api_router.include_router(users.router, prefix="/v1/users", tags=["users"])
api_router.include_router(payment_methods.router, prefix="/v1/payment-methods", tags=["payment-methods"])
api_router.include_router(availability.router, prefix="/v1/availability", tags=["booking-engine"])
api_router.include_router(reservations.router, prefix="/v1/reservations", tags=["reservations"])
api_router.include_router(rooms.router, prefix="/v1/rooms", tags=["rooms"])
api_router.include_router(room_types.router, prefix="/v1/room-types", tags=["room-types"])
api_router.include_router(bookings.router, prefix="/v1/bookings", tags=["bookings"])
api_router.include_router(precheckin.router, prefix="/v1/precheckin", tags=["precheckin"])
api_router.include_router(guests.router, prefix="/v1/guests", tags=["guests"])
api_router.include_router(staff.router, prefix="/v1/staff", tags=["staff"])
api_router.include_router(frontdesk.router, prefix="/v1/frontdesk", tags=["frontdesk"])
api_router.include_router(housekeeping.router, prefix="/v1/housekeeping", tags=["housekeeping"])
api_router.include_router(maintenance.router, prefix="/v1/maintenance", tags=["maintenance"])
api_router.include_router(runner.router, prefix="/v1/runner", tags=["runner"])
api_router.include_router(notifications.router, prefix="/v1/notifications", tags=["notifications"])
api_router.include_router(rates.router, prefix="/v1/rates", tags=["rates"])
api_router.include_router(helpdesk.router, prefix="/v1/help", tags=["help"])
api_router.include_router(reports.router, prefix="/v1/reports", tags=["reports"])
api_router.include_router(dashboards.router, prefix="/v1/dashboards", tags=["dashboards"])
api_router.include_router(admin.router, prefix="/v1/admin", tags=["admin"])
api_router.include_router(otp.router, prefix="/v1/otp", tags=["otp"])
api_router.include_router(guest_ai.router, prefix="/v1/guest-ai", tags=["guest-ai"])
api_router.include_router(guest_assistant.router, prefix="/v1/guest-assistant", tags=["guest-assistant"])
api_router.include_router(agi_assistant.router, prefix="/v1/agi", tags=["agi-assistant"])
api_router.include_router(admin_ai.router, prefix="/v1/admin-ai", tags=["admin-ai"])
api_router.include_router(feedback.router, prefix="/v1/feedback", tags=["feedback"])
api_router.include_router(analytics.router, prefix="/v1/analytics", tags=["advanced-analytics"])
api_router.include_router(revenue_intelligence.router, prefix="/v1/revenue-intelligence", tags=["revenue-intelligence"])
api_router.include_router(reputation.router, prefix="/v1/reputation", tags=["reputation"])
api_router.include_router(reputation_alerts.router, prefix="/v1/reputation/alerts", tags=["reputation-alerts"])
api_router.include_router(reputation_automation.router, prefix="/v1/reputation/automation", tags=["reputation-automation"])
api_router.include_router(reputation_categories.router, prefix="/v1/reputation/categories", tags=["reputation-categories"])
api_router.include_router(reputation_templates.router, prefix="/v1/reputation/templates", tags=["reputation-templates"])
api_router.include_router(crm_ai.router, prefix="/v1/crm-ai", tags=["crm-ai"])
api_router.include_router(crm_ai_extended.router, prefix="/v1/crm-ai", tags=["crm-ai-extended"])
api_router.include_router(overbooking.router, prefix="/v1/overbooking", tags=["overbooking"])
api_router.include_router(guest_chat.router, prefix="/v1/guest-chat", tags=["guest-chat"])
api_router.include_router(inventory.router, prefix="/v1/inventory", tags=["inventory"])
api_router.include_router(attendance.router, prefix="/v1/attendance", tags=["attendance"])
api_router.include_router(folio.router, prefix="/v1/bookings", tags=["folio"])
api_router.include_router(rbac.router, prefix="/v1/rbac", tags=["rbac"])
api_router.include_router(hotel_config.router, prefix="/v1/config", tags=["hotel-config"])
api_router.include_router(tax.router, prefix="/v1/tax", tags=["tax"])
api_router.include_router(corporate.router, prefix="/v1/corporate", tags=["corporate"])
api_router.include_router(ar.router, prefix="/v1/ar", tags=["ar"])
api_router.include_router(preauth.router, prefix="/v1/preauth", tags=["preauth"])
api_router.include_router(transaction_codes.router, prefix="/v1/transaction-codes", tags=["transaction-codes"])
api_router.include_router(audit_log.router, prefix="/v1/audit-logs", tags=["audit-logs"])
api_router.include_router(cashier_session.router, prefix="/v1/cashier-sessions", tags=["cashier-sessions"])
api_router.include_router(room_moves.router, prefix="/v1/room-moves", tags=["room-moves"])
api_router.include_router(paymaster.router, prefix="/v1/paymaster", tags=["paymaster"])
api_router.include_router(pos_closure.router, prefix="/v1/pos-closure", tags=["pos-closure"])
api_router.include_router(audit_pack.router, prefix="/v1/audit-pack", tags=["audit-pack"])
api_router.include_router(multi_room.router, prefix="/v1/multi-room", tags=["multi-room"])


