"""Add RMS Channel Manager Promotions RBAC CRM Extended models

Revision ID: 8eb737cedc30
Revises: 
Create Date: 2026-01-06 23:46:57.971873

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eb737cedc30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_sentiment_by_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('positive_pct', sa.Float(), nullable=False),
    sa.Column('negative_pct', sa.Float(), nullable=False),
    sa.Column('neutral_pct', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_sentiment_by_category', schema=None) as batch_op:
        batch_op.create_index('ix_crm_sentiment_by_category_category_name', ['category_name'], unique=False)
        batch_op.create_index('ix_crm_sentiment_by_category_period_end', ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_sentiment_by_category_period_start'), ['period_start'], unique=False)
        batch_op.create_index('ix_crm_sentiment_by_category_property_category', ['property_id', 'category_name'], unique=False)
        batch_op.create_index('ix_crm_sentiment_by_category_property_id', ['property_id'], unique=False)
        batch_op.create_index('ix_crm_sentiment_by_category_property_period', ['property_id', 'period_start', 'period_end'], unique=False)

    op.create_table('crm_sentiment_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('theme_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_sentiment_themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_sentiment_themes_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_crm_sentiment_themes_mention_count', ['mention_count'], unique=False)
        batch_op.create_index('ix_crm_sentiment_themes_property_id', ['property_id'], unique=False)
        batch_op.create_index('ix_crm_sentiment_themes_property_type', ['property_id', 'theme_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_sentiment_themes_theme_type'), ['theme_type'], unique=False)

    op.create_table('ota_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('ota_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ota_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('connection_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hotel_id_on_ota', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('sync_rates', sa.Boolean(), nullable=False),
    sa.Column('sync_availability', sa.Boolean(), nullable=False),
    sa.Column('sync_restrictions', sa.Boolean(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ota_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ota_connections_auto_sync_enabled'), ['auto_sync_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_connections_connection_status'), ['connection_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_connections_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_ota_connections_next_sync', ['next_sync_at', 'auto_sync_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_connections_next_sync_at'), ['next_sync_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_connections_ota_code'), ['ota_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_connections_property_id'), ['property_id'], unique=False)
        batch_op.create_index('ix_ota_connections_property_ota', ['property_id', 'ota_code'], unique=False)

    op.create_table('rbac_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permission_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rbac_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rbac_permissions_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_rbac_permissions_module', ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_permissions_permission_code'), ['permission_code'], unique=True)

    op.create_table('rbac_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rbac_roles', schema=None) as batch_op:
        batch_op.create_index('ix_rbac_roles_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_rbac_roles_role_code', ['role_code'], unique=False)

    op.create_table('availability_grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('grid_date', sa.Date(), nullable=False),
    sa.Column('total_inventory', sa.Integer(), nullable=False),
    sa.Column('sold', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('rate_amount', sa.Float(), nullable=True),
    sa.Column('min_rate', sa.Float(), nullable=True),
    sa.Column('max_rate', sa.Float(), nullable=True),
    sa.Column('cta_flag', sa.Boolean(), nullable=False),
    sa.Column('ctd_flag', sa.Boolean(), nullable=False),
    sa.Column('stop_sell_flag', sa.Boolean(), nullable=False),
    sa.Column('min_stay', sa.Integer(), nullable=True),
    sa.Column('max_stay', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'room_type_id', 'grid_date', name='uq_availability_grid_date')
    )
    with op.batch_alter_table('availability_grid', schema=None) as batch_op:
        batch_op.create_index('ix_availability_grid_date_range', ['grid_date', 'room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_grid_grid_date'), ['grid_date'], unique=False)
        batch_op.create_index('ix_availability_grid_property_date', ['property_id', 'grid_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_grid_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_grid_room_type_id'), ['room_type_id'], unique=False)

    op.create_table('channel_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('ota_connection_id', sa.Integer(), nullable=True),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('restriction_date', sa.Date(), nullable=False),
    sa.Column('restriction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('restriction_value', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ota_connection_id'], ['ota_connections.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_restrictions', schema=None) as batch_op:
        batch_op.create_index('ix_channel_restrictions_date', ['restriction_date', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_restrictions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_restrictions_ota_connection_id'), ['ota_connection_id'], unique=False)
        batch_op.create_index('ix_channel_restrictions_ota_room', ['ota_connection_id', 'room_type_id', 'restriction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_restrictions_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_restrictions_restriction_date'), ['restriction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_restrictions_restriction_type'), ['restriction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_restrictions_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index('ix_channel_restrictions_type', ['restriction_type', 'restriction_date'], unique=False)

    op.create_table('ota_rate_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('ota_connection_id', sa.Integer(), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('ota_rate_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ota_rate_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('markup_percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ota_connection_id'], ['ota_connections.id'], ),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rateplan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ota_connection_id', 'rate_plan_id', name='uq_ota_rate_mapping')
    )
    with op.batch_alter_table('ota_rate_mappings', schema=None) as batch_op:
        batch_op.create_index('ix_ota_rate_mappings_active', ['is_active', 'ota_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_rate_mappings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_rate_mappings_ota_connection_id'), ['ota_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_rate_mappings_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_rate_mappings_rate_plan_id'), ['rate_plan_id'], unique=False)

    op.create_table('ota_room_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('ota_connection_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('ota_room_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ota_room_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ota_connection_id'], ['ota_connections.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ota_connection_id', 'room_type_id', name='uq_ota_room_mapping')
    )
    with op.batch_alter_table('ota_room_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ota_room_mappings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_room_mappings_ota_connection_id'), ['ota_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_room_mappings_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_room_mappings_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_room_mappings_sync_status'), ['sync_status'], unique=False)

    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('promotion_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discount_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=True),
    sa.Column('max_nights', sa.Integer(), nullable=True),
    sa.Column('min_booking_amount', sa.Float(), nullable=True),
    sa.Column('max_discount_amount', sa.Float(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_stackable', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index('ix_promotions_active_dates', ['is_active', 'valid_from', 'valid_to'], unique=False)
        batch_op.create_index('ix_promotions_code', ['promotion_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_discount_type'), ['discount_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_promotion_code'), ['promotion_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_property_id'), ['property_id'], unique=False)
        batch_op.create_index('ix_promotions_valid_dates', ['valid_from', 'valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_valid_to'), ['valid_to'], unique=False)

    op.create_table('rate_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('ota_connection_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('adjustment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adjustment_value', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ota_connection_id'], ['ota_connections.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_overrides', schema=None) as batch_op:
        batch_op.create_index('ix_rate_overrides_date_range', ['start_date', 'end_date', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_overrides_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_overrides_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_overrides_ota_connection_id'), ['ota_connection_id'], unique=False)
        batch_op.create_index('ix_rate_overrides_ota_room', ['ota_connection_id', 'room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_overrides_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_overrides_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_overrides_start_date'), ['start_date'], unique=False)

    op.create_table('rbac_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rbac_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rbac_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index('ix_rbac_audit_logs_entity_type_id', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_rbac_audit_logs_user_id', ['user_id'], unique=False)

    op.create_table('rbac_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rbac_role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rbac_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_role_permissions_role_id'), ['role_id'], unique=False)
        batch_op.create_index('ix_rbac_role_permissions_role_permission', ['role_id', 'permission_id'], unique=False)

    op.create_table('rbac_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rbac_user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rbac_user_roles_assigned_at'), ['assigned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_user_roles_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_rbac_user_roles_user_role', ['user_id', 'role_id'], unique=False)

    op.create_table('rbac_user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rbac_user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rbac_user_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_user_sessions_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_user_sessions_login_at'), ['login_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbac_user_sessions_logout_at'), ['logout_at'], unique=False)
        batch_op.create_index('ix_rbac_user_sessions_session_token', ['session_token'], unique=False)
        batch_op.create_index('ix_rbac_user_sessions_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('ix_rbac_user_sessions_user_id', ['user_id'], unique=False)

    op.create_table('rms_competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('google_place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('booking_com_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tripadvisor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rms_competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rms_competitors_booking_com_id'), ['booking_com_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitors_google_place_id'), ['google_place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitors_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitors_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitors_tripadvisor_id'), ['tripadvisor_id'], unique=False)

    op.create_table('rms_market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('impact_multiplier', sa.Float(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rms_market_events', schema=None) as batch_op:
        batch_op.create_index('ix_market_events_dates', ['property_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_market_events_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_market_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_market_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_market_events_is_recurring'), ['is_recurring'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_market_events_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_market_events_start_date'), ['start_date'], unique=False)

    op.create_table('rms_pickup_pace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('days_out', sa.Integer(), nullable=False),
    sa.Column('current_bookings', sa.Integer(), nullable=False),
    sa.Column('expected_total', sa.Integer(), nullable=True),
    sa.Column('predicted_final', sa.Integer(), nullable=True),
    sa.Column('booking_progress_pct', sa.Float(), nullable=True),
    sa.Column('pace_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ly_bookings', sa.Integer(), nullable=True),
    sa.Column('ly_variance_pct', sa.Float(), nullable=True),
    sa.Column('lw_bookings', sa.Integer(), nullable=True),
    sa.Column('lw_variance_pct', sa.Float(), nullable=True),
    sa.Column('alerts', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rms_pickup_pace', schema=None) as batch_op:
        batch_op.create_index('ix_pickup_pace_arrival_snapshot', ['property_id', 'arrival_date', 'snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_pickup_pace_arrival_date'), ['arrival_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_pickup_pace_days_out'), ['days_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_pickup_pace_pace_status'), ['pace_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_pickup_pace_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_pickup_pace_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('rms_pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('room_types', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('times_triggered', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rms_pricing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rms_pricing_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_pricing_rules_last_triggered_at'), ['last_triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_pricing_rules_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_pricing_rules_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_pricing_rules_rule_name'), ['rule_name'], unique=False)

    op.create_table('rms_segment_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('segment_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('room_nights', sa.Integer(), nullable=False),
    sa.Column('bookings', sa.Integer(), nullable=False),
    sa.Column('adr', sa.Float(), nullable=True),
    sa.Column('revpar', sa.Float(), nullable=True),
    sa.Column('cancellations', sa.Integer(), nullable=False),
    sa.Column('cancel_rate_pct', sa.Float(), nullable=True),
    sa.Column('revenue_contribution_pct', sa.Float(), nullable=True),
    sa.Column('avg_lead_time_days', sa.Float(), nullable=True),
    sa.Column('avg_los', sa.Float(), nullable=True),
    sa.Column('yoy_variance_pct', sa.Float(), nullable=True),
    sa.Column('optimizations', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['market_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rms_segment_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rms_segment_performance_period_month'), ['period_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_segment_performance_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_segment_performance_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_segment_performance_segment_name'), ['segment_name'], unique=False)
        batch_op.create_index('ix_segment_perf_property_period', ['property_id', 'period_month'], unique=False)
        batch_op.create_index('ix_segment_perf_segment_period', ['segment_id', 'period_month'], unique=False)

    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('ota_connection_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sync_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ota_connection_id'], ['ota_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_logs_ota_connection_id'), ['ota_connection_id'], unique=False)
        batch_op.create_index('ix_sync_logs_ota_date', ['ota_connection_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_started_at'), ['started_at'], unique=False)
        batch_op.create_index('ix_sync_logs_status', ['status', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_sync_direction'), ['sync_direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_sync_type'), ['sync_type'], unique=False)
        batch_op.create_index('ix_sync_logs_type_direction', ['sync_type', 'sync_direction'], unique=False)

    op.create_table('crm_guest_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_guest_activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_guest_activity_logs_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index('ix_crm_guest_activity_logs_guest_id', ['guest_id'], unique=False)
        batch_op.create_index('ix_crm_guest_activity_logs_guest_property', ['guest_id', 'property_id'], unique=False)
        batch_op.create_index('ix_crm_guest_activity_logs_platform', ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_guest_activity_logs_property_id'), ['property_id'], unique=False)
        batch_op.create_index('ix_crm_guest_activity_logs_related_entity', ['related_entity_type', 'related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_guest_activity_logs_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_guest_activity_logs_related_entity_type'), ['related_entity_type'], unique=False)
        batch_op.create_index('ix_crm_guest_activity_logs_timestamp', ['timestamp'], unique=False)

    op.create_table('crm_guest_ltv_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_stays', sa.Integer(), nullable=False),
    sa.Column('total_nights', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('avg_spend_per_stay', sa.Float(), nullable=False),
    sa.Column('avg_nights_per_stay', sa.Float(), nullable=False),
    sa.Column('first_stay_date', sa.Date(), nullable=True),
    sa.Column('last_stay_date', sa.Date(), nullable=True),
    sa.Column('days_since_last_stay', sa.Integer(), nullable=True),
    sa.Column('predicted_ltv', sa.Float(), nullable=True),
    sa.Column('ltv_segment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_guest_ltv_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_crm_guest_ltv_snapshots_guest_date', ['guest_id', 'snapshot_date'], unique=False)
        batch_op.create_index('ix_crm_guest_ltv_snapshots_guest_id', ['guest_id'], unique=False)
        batch_op.create_index('ix_crm_guest_ltv_snapshots_guest_property', ['guest_id', 'property_id'], unique=False)
        batch_op.create_index('ix_crm_guest_ltv_snapshots_ltv_segment', ['ltv_segment'], unique=False)
        batch_op.create_index('ix_crm_guest_ltv_snapshots_property_id', ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_guest_ltv_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('promotion_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('analytics_date', sa.Date(), nullable=False),
    sa.Column('redemptions', sa.Integer(), nullable=False),
    sa.Column('revenue_generated', sa.Float(), nullable=False),
    sa.Column('incremental_revenue', sa.Float(), nullable=True),
    sa.Column('adr_uplift_pct', sa.Float(), nullable=True),
    sa.Column('occupancy_impact_pct', sa.Float(), nullable=True),
    sa.Column('channel_breakdown', sa.JSON(), nullable=True),
    sa.Column('room_type_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_analytics', schema=None) as batch_op:
        batch_op.create_index('ix_promo_analytics_date', ['analytics_date'], unique=False)
        batch_op.create_index('ix_promo_analytics_promo_date', ['promotion_id', 'analytics_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_analytics_analytics_date'), ['analytics_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_analytics_promotion_id'), ['promotion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_analytics_property_id'), ['property_id'], unique=False)

    op.create_table('promotion_applicability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_applicability', schema=None) as batch_op:
        batch_op.create_index('ix_promo_applicability_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_applicability_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_applicability_promotion_id'), ['promotion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_applicability_property_id'), ['property_id'], unique=False)

    op.create_table('promotion_blackout_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('blackout_start', sa.Date(), nullable=False),
    sa.Column('blackout_end', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_blackout_dates', schema=None) as batch_op:
        batch_op.create_index('ix_promo_blackout_dates', ['blackout_start', 'blackout_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_blackout_dates_blackout_end'), ['blackout_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_blackout_dates_blackout_start'), ['blackout_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_blackout_dates_promotion_id'), ['promotion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_blackout_dates_property_id'), ['property_id'], unique=False)

    op.create_table('rms_competitor_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('room_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rate_amount', sa.Float(), nullable=False),
    sa.Column('rate_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['rms_competitors.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rms_competitor_rates', schema=None) as batch_op:
        batch_op.create_index('ix_competitor_rates_date_competitor', ['competitor_id', 'rate_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitor_rates_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitor_rates_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitor_rates_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitor_rates_rate_date'), ['rate_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitor_rates_rate_source'), ['rate_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_competitor_rates_room_type'), ['room_type'], unique=False)

    op.create_table('rms_demand_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('days_out', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('demand_index', sa.Float(), nullable=False),
    sa.Column('demand_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('forecasted_occupancy', sa.Float(), nullable=True),
    sa.Column('forecasted_adr', sa.Float(), nullable=True),
    sa.Column('forecasted_revpar', sa.Float(), nullable=True),
    sa.Column('forecasted_revenue', sa.Float(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('price_recommendation', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('yoy_comparison', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['rms_market_events.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rms_demand_forecasts', schema=None) as batch_op:
        batch_op.create_index('ix_demand_forecast_date_property', ['property_id', 'forecast_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_demand_forecasts_days_out'), ['days_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_demand_forecasts_demand_level'), ['demand_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_demand_forecasts_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_demand_forecasts_forecast_date'), ['forecast_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_demand_forecasts_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rms_demand_forecasts_property_id'), ['property_id'], unique=False)

    op.create_table('promotion_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['hotel_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_usage', schema=None) as batch_op:
        batch_op.create_index('ix_promo_usage_booking', ['booking_id'], unique=False)
        batch_op.create_index('ix_promo_usage_guest', ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_usage_applied_at'), ['applied_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_usage_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_usage_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_usage_promotion_id'), ['promotion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_usage_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_flag', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('number_of_guests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upsells', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('discount_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('net_revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('modification_count', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_bookings_discount_code'), ['discount_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_vip_flag'), ['vip_flag'], unique=False)
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('housekeeping_tasks', schema=None) as batch_op:
        batch_op.alter_column('force_assigned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_housekeeping_tasks_acceptance_status'), ['acceptance_status'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['force_assigned_by'], ['id'])

    with op.batch_alter_table('maintenancerequest', schema=None) as batch_op:
        batch_op.alter_column('is_preventive',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('force_assigned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index('idx_maintenancerequest_issue_type')
        batch_op.drop_index('idx_maintenancerequest_room_number')
        batch_op.create_index(batch_op.f('ix_maintenancerequest_acceptance_status'), ['acceptance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenancerequest_is_preventive'), ['is_preventive'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenancerequest_issue_type'), ['issue_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenancerequest_preventive_schedule_id'), ['preventive_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenancerequest_room_number'), ['room_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenancerequest_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['force_assigned_by'], ['id'])

    with op.batch_alter_table('room_holds', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_room_holds_dates')
        batch_op.drop_index('idx_room_holds_status')
        batch_op.drop_index('idx_room_holds_token')
        batch_op.create_index(batch_op.f('ix_room_holds_arrival_date'), ['arrival_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_holds_departure_date'), ['departure_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_holds_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_holds_hold_token'), ['hold_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_room_holds_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_holds_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_holds_status'), ['status'], unique=False)
        batch_op.drop_column('HOLD_DURATION_MINUTES')

    with op.batch_alter_table('staffnotification', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('notification_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'task_assigned'"))
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffnotification', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('notification_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'task_assigned'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('room_holds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('HOLD_DURATION_MINUTES', sa.INTEGER(), server_default=sa.text('(15)'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_room_holds_status'))
        batch_op.drop_index(batch_op.f('ix_room_holds_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_room_holds_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_holds_hold_token'))
        batch_op.drop_index(batch_op.f('ix_room_holds_expires_at'))
        batch_op.drop_index(batch_op.f('ix_room_holds_departure_date'))
        batch_op.drop_index(batch_op.f('ix_room_holds_arrival_date'))
        batch_op.create_index('idx_room_holds_token', ['hold_token'], unique=False)
        batch_op.create_index('idx_room_holds_status', ['status', 'expires_at'], unique=False)
        batch_op.create_index('idx_room_holds_dates', ['arrival_date', 'departure_date'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('maintenancerequest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_maintenancerequest_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_maintenancerequest_room_number'))
        batch_op.drop_index(batch_op.f('ix_maintenancerequest_preventive_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_maintenancerequest_issue_type'))
        batch_op.drop_index(batch_op.f('ix_maintenancerequest_is_preventive'))
        batch_op.drop_index(batch_op.f('ix_maintenancerequest_acceptance_status'))
        batch_op.create_index('idx_maintenancerequest_room_number', ['room_number'], unique=False)
        batch_op.create_index('idx_maintenancerequest_issue_type', ['issue_type'], unique=False)
        batch_op.alter_column('force_assigned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_preventive',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('housekeeping_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_housekeeping_tasks_acceptance_status'))
        batch_op.alter_column('force_assigned',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.REAL(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_bookings_vip_flag'))
        batch_op.drop_index(batch_op.f('ix_bookings_discount_code'))
        batch_op.drop_column('modification_count')
        batch_op.drop_column('net_revenue')
        batch_op.drop_column('commission_amount')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_code')
        batch_op.drop_column('upsells')
        batch_op.drop_column('number_of_guests')
        batch_op.drop_column('vip_flag')

    with op.batch_alter_table('promotion_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_usage_property_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_usage_promotion_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_usage_guest_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_usage_booking_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_usage_applied_at'))
        batch_op.drop_index('ix_promo_usage_guest')
        batch_op.drop_index('ix_promo_usage_booking')

    op.drop_table('promotion_usage')
    with op.batch_alter_table('rms_demand_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rms_demand_forecasts_property_id'))
        batch_op.drop_index(batch_op.f('ix_rms_demand_forecasts_generated_at'))
        batch_op.drop_index(batch_op.f('ix_rms_demand_forecasts_forecast_date'))
        batch_op.drop_index(batch_op.f('ix_rms_demand_forecasts_event_id'))
        batch_op.drop_index(batch_op.f('ix_rms_demand_forecasts_demand_level'))
        batch_op.drop_index(batch_op.f('ix_rms_demand_forecasts_days_out'))
        batch_op.drop_index('ix_demand_forecast_date_property')

    op.drop_table('rms_demand_forecasts')
    with op.batch_alter_table('rms_competitor_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rms_competitor_rates_room_type'))
        batch_op.drop_index(batch_op.f('ix_rms_competitor_rates_rate_source'))
        batch_op.drop_index(batch_op.f('ix_rms_competitor_rates_rate_date'))
        batch_op.drop_index(batch_op.f('ix_rms_competitor_rates_property_id'))
        batch_op.drop_index(batch_op.f('ix_rms_competitor_rates_competitor_id'))
        batch_op.drop_index(batch_op.f('ix_rms_competitor_rates_captured_at'))
        batch_op.drop_index('ix_competitor_rates_date_competitor')

    op.drop_table('rms_competitor_rates')
    with op.batch_alter_table('promotion_blackout_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_blackout_dates_property_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_blackout_dates_promotion_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_blackout_dates_blackout_start'))
        batch_op.drop_index(batch_op.f('ix_promotion_blackout_dates_blackout_end'))
        batch_op.drop_index('ix_promo_blackout_dates')

    op.drop_table('promotion_blackout_dates')
    with op.batch_alter_table('promotion_applicability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_applicability_property_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_applicability_promotion_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_applicability_entity_type'))
        batch_op.drop_index('ix_promo_applicability_entity')

    op.drop_table('promotion_applicability')
    with op.batch_alter_table('promotion_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_analytics_property_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_analytics_promotion_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_analytics_analytics_date'))
        batch_op.drop_index('ix_promo_analytics_promo_date')
        batch_op.drop_index('ix_promo_analytics_date')

    op.drop_table('promotion_analytics')
    with op.batch_alter_table('crm_guest_ltv_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_guest_ltv_snapshots_snapshot_date'))
        batch_op.drop_index('ix_crm_guest_ltv_snapshots_property_id')
        batch_op.drop_index('ix_crm_guest_ltv_snapshots_ltv_segment')
        batch_op.drop_index('ix_crm_guest_ltv_snapshots_guest_property')
        batch_op.drop_index('ix_crm_guest_ltv_snapshots_guest_id')
        batch_op.drop_index('ix_crm_guest_ltv_snapshots_guest_date')

    op.drop_table('crm_guest_ltv_snapshots')
    with op.batch_alter_table('crm_guest_activity_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_crm_guest_activity_logs_timestamp')
        batch_op.drop_index(batch_op.f('ix_crm_guest_activity_logs_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_crm_guest_activity_logs_related_entity_id'))
        batch_op.drop_index('ix_crm_guest_activity_logs_related_entity')
        batch_op.drop_index(batch_op.f('ix_crm_guest_activity_logs_property_id'))
        batch_op.drop_index('ix_crm_guest_activity_logs_platform')
        batch_op.drop_index('ix_crm_guest_activity_logs_guest_property')
        batch_op.drop_index('ix_crm_guest_activity_logs_guest_id')
        batch_op.drop_index(batch_op.f('ix_crm_guest_activity_logs_activity_type'))

    op.drop_table('crm_guest_activity_logs')
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_logs_type_direction')
        batch_op.drop_index(batch_op.f('ix_sync_logs_sync_type'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_sync_direction'))
        batch_op.drop_index('ix_sync_logs_status')
        batch_op.drop_index(batch_op.f('ix_sync_logs_started_at'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_property_id'))
        batch_op.drop_index('ix_sync_logs_ota_date')
        batch_op.drop_index(batch_op.f('ix_sync_logs_ota_connection_id'))

    op.drop_table('sync_logs')
    with op.batch_alter_table('rms_segment_performance', schema=None) as batch_op:
        batch_op.drop_index('ix_segment_perf_segment_period')
        batch_op.drop_index('ix_segment_perf_property_period')
        batch_op.drop_index(batch_op.f('ix_rms_segment_performance_segment_name'))
        batch_op.drop_index(batch_op.f('ix_rms_segment_performance_segment_id'))
        batch_op.drop_index(batch_op.f('ix_rms_segment_performance_property_id'))
        batch_op.drop_index(batch_op.f('ix_rms_segment_performance_period_month'))

    op.drop_table('rms_segment_performance')
    with op.batch_alter_table('rms_pricing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rms_pricing_rules_rule_name'))
        batch_op.drop_index(batch_op.f('ix_rms_pricing_rules_property_id'))
        batch_op.drop_index(batch_op.f('ix_rms_pricing_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_rms_pricing_rules_last_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_rms_pricing_rules_is_active'))

    op.drop_table('rms_pricing_rules')
    with op.batch_alter_table('rms_pickup_pace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rms_pickup_pace_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_rms_pickup_pace_property_id'))
        batch_op.drop_index(batch_op.f('ix_rms_pickup_pace_pace_status'))
        batch_op.drop_index(batch_op.f('ix_rms_pickup_pace_days_out'))
        batch_op.drop_index(batch_op.f('ix_rms_pickup_pace_arrival_date'))
        batch_op.drop_index('ix_pickup_pace_arrival_snapshot')

    op.drop_table('rms_pickup_pace')
    with op.batch_alter_table('rms_market_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rms_market_events_start_date'))
        batch_op.drop_index(batch_op.f('ix_rms_market_events_property_id'))
        batch_op.drop_index(batch_op.f('ix_rms_market_events_is_recurring'))
        batch_op.drop_index(batch_op.f('ix_rms_market_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_rms_market_events_event_name'))
        batch_op.drop_index(batch_op.f('ix_rms_market_events_end_date'))
        batch_op.drop_index('ix_market_events_dates')

    op.drop_table('rms_market_events')
    with op.batch_alter_table('rms_competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rms_competitors_tripadvisor_id'))
        batch_op.drop_index(batch_op.f('ix_rms_competitors_property_id'))
        batch_op.drop_index(batch_op.f('ix_rms_competitors_name'))
        batch_op.drop_index(batch_op.f('ix_rms_competitors_is_active'))
        batch_op.drop_index(batch_op.f('ix_rms_competitors_google_place_id'))
        batch_op.drop_index(batch_op.f('ix_rms_competitors_booking_com_id'))

    op.drop_table('rms_competitors')
    with op.batch_alter_table('rbac_user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_rbac_user_sessions_user_id')
        batch_op.drop_index('ix_rbac_user_sessions_user_active')
        batch_op.drop_index('ix_rbac_user_sessions_session_token')
        batch_op.drop_index(batch_op.f('ix_rbac_user_sessions_logout_at'))
        batch_op.drop_index(batch_op.f('ix_rbac_user_sessions_login_at'))
        batch_op.drop_index(batch_op.f('ix_rbac_user_sessions_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_rbac_user_sessions_is_active'))

    op.drop_table('rbac_user_sessions')
    with op.batch_alter_table('rbac_user_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_rbac_user_roles_user_role')
        batch_op.drop_index(batch_op.f('ix_rbac_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_rbac_user_roles_role_id'))
        batch_op.drop_index(batch_op.f('ix_rbac_user_roles_assigned_at'))

    op.drop_table('rbac_user_roles')
    with op.batch_alter_table('rbac_role_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_rbac_role_permissions_role_permission')
        batch_op.drop_index(batch_op.f('ix_rbac_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_rbac_role_permissions_permission_id'))

    op.drop_table('rbac_role_permissions')
    with op.batch_alter_table('rbac_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_rbac_audit_logs_user_id')
        batch_op.drop_index('ix_rbac_audit_logs_entity_type_id')
        batch_op.drop_index(batch_op.f('ix_rbac_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_rbac_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_rbac_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_rbac_audit_logs_action_type'))

    op.drop_table('rbac_audit_logs')
    with op.batch_alter_table('rate_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_overrides_start_date'))
        batch_op.drop_index(batch_op.f('ix_rate_overrides_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_rate_overrides_property_id'))
        batch_op.drop_index('ix_rate_overrides_ota_room')
        batch_op.drop_index(batch_op.f('ix_rate_overrides_ota_connection_id'))
        batch_op.drop_index(batch_op.f('ix_rate_overrides_is_active'))
        batch_op.drop_index(batch_op.f('ix_rate_overrides_end_date'))
        batch_op.drop_index('ix_rate_overrides_date_range')

    op.drop_table('rate_overrides')
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotions_valid_to'))
        batch_op.drop_index(batch_op.f('ix_promotions_valid_from'))
        batch_op.drop_index('ix_promotions_valid_dates')
        batch_op.drop_index(batch_op.f('ix_promotions_property_id'))
        batch_op.drop_index(batch_op.f('ix_promotions_promotion_code'))
        batch_op.drop_index(batch_op.f('ix_promotions_priority'))
        batch_op.drop_index(batch_op.f('ix_promotions_is_active'))
        batch_op.drop_index(batch_op.f('ix_promotions_discount_type'))
        batch_op.drop_index(batch_op.f('ix_promotions_created_at'))
        batch_op.drop_index('ix_promotions_code')
        batch_op.drop_index('ix_promotions_active_dates')

    op.drop_table('promotions')
    with op.batch_alter_table('ota_room_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ota_room_mappings_sync_status'))
        batch_op.drop_index(batch_op.f('ix_ota_room_mappings_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_ota_room_mappings_property_id'))
        batch_op.drop_index(batch_op.f('ix_ota_room_mappings_ota_connection_id'))
        batch_op.drop_index(batch_op.f('ix_ota_room_mappings_is_active'))

    op.drop_table('ota_room_mappings')
    with op.batch_alter_table('ota_rate_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ota_rate_mappings_rate_plan_id'))
        batch_op.drop_index(batch_op.f('ix_ota_rate_mappings_property_id'))
        batch_op.drop_index(batch_op.f('ix_ota_rate_mappings_ota_connection_id'))
        batch_op.drop_index(batch_op.f('ix_ota_rate_mappings_is_active'))
        batch_op.drop_index('ix_ota_rate_mappings_active')

    op.drop_table('ota_rate_mappings')
    with op.batch_alter_table('channel_restrictions', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_restrictions_type')
        batch_op.drop_index(batch_op.f('ix_channel_restrictions_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_channel_restrictions_restriction_type'))
        batch_op.drop_index(batch_op.f('ix_channel_restrictions_restriction_date'))
        batch_op.drop_index(batch_op.f('ix_channel_restrictions_property_id'))
        batch_op.drop_index('ix_channel_restrictions_ota_room')
        batch_op.drop_index(batch_op.f('ix_channel_restrictions_ota_connection_id'))
        batch_op.drop_index(batch_op.f('ix_channel_restrictions_is_active'))
        batch_op.drop_index('ix_channel_restrictions_date')

    op.drop_table('channel_restrictions')
    with op.batch_alter_table('availability_grid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_grid_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_availability_grid_property_id'))
        batch_op.drop_index('ix_availability_grid_property_date')
        batch_op.drop_index(batch_op.f('ix_availability_grid_grid_date'))
        batch_op.drop_index('ix_availability_grid_date_range')

    op.drop_table('availability_grid')
    with op.batch_alter_table('rbac_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_rbac_roles_role_code')
        batch_op.drop_index('ix_rbac_roles_is_active')

    op.drop_table('rbac_roles')
    with op.batch_alter_table('rbac_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rbac_permissions_permission_code'))
        batch_op.drop_index('ix_rbac_permissions_module')
        batch_op.drop_index(batch_op.f('ix_rbac_permissions_is_active'))

    op.drop_table('rbac_permissions')
    with op.batch_alter_table('ota_connections', schema=None) as batch_op:
        batch_op.drop_index('ix_ota_connections_property_ota')
        batch_op.drop_index(batch_op.f('ix_ota_connections_property_id'))
        batch_op.drop_index(batch_op.f('ix_ota_connections_ota_code'))
        batch_op.drop_index(batch_op.f('ix_ota_connections_next_sync_at'))
        batch_op.drop_index('ix_ota_connections_next_sync')
        batch_op.drop_index(batch_op.f('ix_ota_connections_is_active'))
        batch_op.drop_index(batch_op.f('ix_ota_connections_connection_status'))
        batch_op.drop_index(batch_op.f('ix_ota_connections_auto_sync_enabled'))

    op.drop_table('ota_connections')
    with op.batch_alter_table('crm_sentiment_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_sentiment_themes_theme_type'))
        batch_op.drop_index('ix_crm_sentiment_themes_property_type')
        batch_op.drop_index('ix_crm_sentiment_themes_property_id')
        batch_op.drop_index('ix_crm_sentiment_themes_mention_count')
        batch_op.drop_index(batch_op.f('ix_crm_sentiment_themes_is_active'))

    op.drop_table('crm_sentiment_themes')
    with op.batch_alter_table('crm_sentiment_by_category', schema=None) as batch_op:
        batch_op.drop_index('ix_crm_sentiment_by_category_property_period')
        batch_op.drop_index('ix_crm_sentiment_by_category_property_id')
        batch_op.drop_index('ix_crm_sentiment_by_category_property_category')
        batch_op.drop_index(batch_op.f('ix_crm_sentiment_by_category_period_start'))
        batch_op.drop_index('ix_crm_sentiment_by_category_period_end')
        batch_op.drop_index('ix_crm_sentiment_by_category_category_name')

    op.drop_table('crm_sentiment_by_category')
    # ### end Alembic commands ###
